server:
  port: 8800
mybatis-plus:
  mapper-locations: classpath:com/ys/oa/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 查看日志
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ys-oa?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8
    username: root
    password: root
  jackson:
    # 统一处理时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: localhost
    port: 6379
    # 默认使用0号数据库 改为1号 数据少 方便清理
    database: 1
    timeout: 1800000
    password: 123456
    # springboot2.x中默认使用lettuce 但这儿换成lettuce会报错
    #
#    jedis:
#      pool:
#        max-active: 20 #最大连接数
#        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
#        max-idle: 5    #最大空闲
#        min-idle: 0     #最小空闲
  activiti:
    #    false:默认，数据库表不变，但是如果版本不对或者缺失表会抛出异常（生产使用）
    #    true:表不存在，自动创建（开发使用）
    #    create_drop: 启动时创建，关闭时删除表（测试使用）
    #    drop_create: 启动时删除表,在创建表 （不需要手动关闭引擎）
    database-schema-update: true
    #监测历史表是否存在，activities7默认不开启历史表
    db-history-used: true
    #none：不保存任何历史数据，流程中这是最高效的
    #activity：只保存流程实例和流程行为
    #audit：除了activity，还保存全部的流程任务以及其属性，audit为history默认值
    #full：除了audit、还保存其他全部流程相关的细节数据，包括一些流程参数
    history-level: full
    #校验流程文件，默认校验resources下的process 文件夹的流程文件
    check-process-definitions: true
wechat:
  mpAppId: wx4268fd6656d177d9
  mpAppSecret: 07634c6a492a9c5d66a10be81cb8a97a
  userInfoUrl: https://3f41-183-230-242-250.ngrok-free.app/admin/wechat/userInfo